name: Model ops deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [ml_ci_cd]

jobs:
  ml_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: python version
        run: python --version
      - name: pip install
        run: pip install -r requirements.txt
        working-directory: deploy-ml
      - name: download dataset
        run: wget -O data/heart_disease.csv ${{github.event.client_payload.dataseturl}}
        working-directory: deploy-ml
      - name: cat dataset
        run: cat data/heart_disease.csv
        working-directory: deploy-ml
      - name: train model
        run: python model/train.py
        working-directory: deploy-ml
      - name: docker build
        run: docker build -t ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha}} .
        working-directory: deploy-ml
      - name: show images
        run: docker images
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.event.client_payload.sha }}
      - name: update docker user in k8
        run: sed -i 's/{docker_user}/${{secrets.DOCKER_USER}}/g' manifests/k8s.yml
        working-directory: deploy-ml
      - name: update model name in k8
        run: sed -i 's/{model_name}/${{secrets.MODEL_NAME}}/g' manifests/k8s.yml
        working-directory: deploy-ml
      - name: update _ by -
        run: sed -i 's/_/-/g' manifests/k8s.yml
        working-directory: deploy-ml
      - name: update sha in k8
        run: sed -i 's/{github.sha}/${{github.event.client_payload.sha }}/g' manifests/k8s.yml
        working-directory: deploy-ml
      - name: show k8s.yml
        run: cat manifests/k8s.yml
        working-directory: deploy-ml
      - uses: okteto/context@2.7.0
        with:
          token: ${{secrets.OKTETO_TOKEN }}

      - name: Deploy and Wait
        uses: okteto/actions/deploy@v1
        env:
          KUBECONFIG: ${{ steps.namespace.outputs.kubeconfig }}
        with:
          namespace: ${{secrets.OKTETO_NAMESPACE }}
          manifest: deploy-ml/manifests/k8s.yml
          tag: ${{ secrets.DOCKER_USERNAME }}/${{secrets.MODEL_NAME}}:${{ github.sha }}
